mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static #추가
from django.conf import settings #추가

from mysite.views import HomeView, MainView, ManualView, DoneeView, DonorView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='videopage_ex'),
    url(r'^main/$', MainView.as_view(), name='mainpage_ex'),
    url(r'^manual/$', ManualView.as_view(), name='manual_home'),
    url(r'^donee/$', DoneeView.as_view(), name='manual_donee'),
    url(r'^donor/$', DonorView.as_view(), name='manual_donor'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^photo/', include('photo.urls', namespace='photo')), #추가

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #추가

photo/urls.py
from django.conf.urls import url

from photo.views import *
app_name = 'photo'
urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

templates/index.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
    <head>
    
        <meta charset="utf-8">
            <meta name="viewport" content="width-device-width, initial-scale=1">
            <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

            <!-- jQuery library -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Thasadith" rel="stylesheet">
            <style>
                body{
                    margin: 0;
                    font-family: 'Lato', sans-serif;
                }
                h1{
                    font-family: 'Thasadith', sans-serif;
                    font-family: 'Lato', sans-serif;
                    font-family: 'Open Sans', sans-serif;
                }
                #myVideo{
                    position: fixed;
                    right: 0;
                    bottom: 0;
                    min-height: 100%;
                    min-width: 100%; 
                }
                .content{
                    position: fixed;
                    width: 100%;
                    background: rgba(0,0,0, 0.3);
                    bottom: 300px;
                    padding: 50px;
                }
                h1{
                    color: orangered;
                    text-align: center;
                    font-size: 5em;
                }
                h4{
                    color:orangered;
                    text-align: center;
                    font-size: 2em;
                }
            </style>
    
    </head>
    <body>
        <a href="{% url 'mainpage_ex' %}">
        <video autoplay loop muted id="myVideo">
            <source src="{% static 'video/NIKE.mp4' %}" type="video/mp4">
        
        </video>
        </a>
        <a href="{% url 'mainpage_ex' %}">
        <div class="content">
            <h1><b>DONOR_HUB</b></h1>
            <br>
            <h4><b>Our vision is that every child will be able to play basketball without any restrictions.</b></h4>
        
        </div>
        </a>
    </body>

templates/mainpage_ex.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang = "en">
    <head>
        <title>Donor-Hub</title>
        <meta charset = "utf-8">
        <meta name = "viewport" content = "weidth=device-width, initial-scale = 1">
        <!-- Latest compiled and minified CSS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style>
            .jumbotron{
                background-color: orangered;
                color:white;
            }
            .bg-grey{
                background-color: #f6f6f6;
            }
            .container-fluid{
                padding: 30px 50px
            }
            .logo{
                color: orangered;
                font-size : 200px;
            }
            .logo-small{
                color:orangered;
                font-size: 50px;
            }
            .thumbnail{
                padding: 0 0 15px 0 ;
                border: none;
                border-radius: 0;
            }
            .thumbnail img{
                width: 100%;
                height: 300px;
                margin-bottom: 10px;
            }
            .carousel-control, .carousel-control.left{
                background-image: none;
                color: #f4511e;
            }
            .carousel-indicators li{
                border-color: #f4511e;
            }
            .carousel-indicators li.active{
                background-color: #f4511e;
            }
            .item h4{
                font-size: 19px;
                font-style: italic;
                margin: 70px 0;
            }
            #myCarousel2_img{
                width: 400px;
                height: 230px;
                margin-left: auto;
                margin-right: auto;
            }
            .panel{
                border: 1px solid #f4511e;
                border-radius:0;
                transition: box-shadow 0.5s;
            }
            .panel:hover{
                box-shadow: 5px 5px 40px lightgray;
            }
            .panel-footer .btn:hover{
                border: 1px solid #f4511e;
                background-color: #fff;
                color: #f4511e;
            }
            .panel-heading{
                color: #f4511e !important;
                background-color:#f4511e !important;
                padding: 25px;
            }
            .panel-footer{
                background-color: #fff !important;
            }
            .panel-footer h3{
                font-size: 32px;
            }
            .panel-footer h4{
                color: #aaa;
                font-size: 14px;
            }
            .panel-footer .btn{
                margin: 15px 0;
                background-color: #f4511e;
                color: #fff;
            }
            .navbar{
                background-color: #fff;
                border: 0;
                font-size: 12px;
                letter-spacing: 4px;
            }
            .navbar li a, .navbar .navbar-brand{
                color: #f4511e !important;
            }
            .navbar-nav li a:hover, .navbar-nav li.active a{
                color: #fff !important;
                background-color: #f4511e !important;
             }
            .navbar-default .navbar-toggle{
                border-color: transparent;
            }
            footer .glyphicon{
                font-size: 20px;
                margin-bottom: 20px;
                color: #f4511e;
            }
            body{
                font-family: Lato, sans-serif;
            }
            .jumbotron{
                font-family: Montserrat, sans-serif;
            }
            .navbar{
                font-family: Montserrat, sans-serif;
            }
           
        </style>
    
    </head>
    <body id="myPage" data-spy="scroll" data-target=".navbar">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'mainpage_ex' %}">DONOR-HUB</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#about">ABOUT</a></li>

                        <li><a href="#portfolio">PORTFOLIO</a></li>
                        <li><a href="{% url 'manual_home' %}">MANUAL</a> </li>

                        {% if user.is_active %}
                        <li><a href="{% url 'password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'logout' %}">LOGOUT</a></li>
                        {% else %}
                        <li><a href="{% url 'register' %}">JOIN</a></li>
                        <li><a href="{% url 'login' %}">LOGIN</a></li>
                        {% endif %}
                        <li><a href="{% url 'photo:index' %}">THE HUB</a></li>
                        {% firstof user.get_short_name user.get_username %}
                    </ul>

                </div>


            </div>
        </nav>
        
        <div class = "jumbotron text-center">
            <h1>DONOR-HUB</h1> <br>
            <p>We create dreams. </p>
        </div>
        
        <div id="about" class = "container-fluid">
            <div class = "row">
                <div class = "col-sm-8">
                    <h2>About DONOR-HUB</h2>
                    <h4>We are a non-profit organization that was founded mainly as a donation foundation to give children with unfortunate backgrounds free gear.</h4>
                    <p>We will be receiving shoes, sport clothes, headbands, wristbands, and other gear related to playing baksetball as donations.  </p>
                </div>
                <div class = "col-sm-4">
                    <span class = "glyphicon glyphicon-heart logo"></span>
                </div>
            </div>
        </div>
        
        <div class = "container-fuild bg-grey">
            <div class = "row">
                <div class = "col-sm-4">
                    <span class = "glyphicon glyphicon-globe logo"></span>
                </div>
                <div class = "col-sm-8">
                    <h2>Our Values</h2>
                    <h4><strong>MISSION:</strong> Our mission is to give every kid the opportunity to reach a higher level in their passions.
                        We focus on giving children sufficient gear in order to play their favorite sports.</h4>
                    <h4><strong>VISION:</strong> Our vision is that every child will be able to play sports.</h4>
                </div>
            </div>
        </div>
        <div id="about1" class = "container-fluid">
            <div class = "row">
                <div class = "col-sm-8">
                    <h2>What We Offer</h2>
                    <h4><strong>DONEES:</strong> Donees simply have sign up to DONOR-HUB to receive free basketball gear such as shoes and clothes.
                        We offer goods based on supplies, but we generally give once a month. </h4>
                    <h4><strong>DONORS:</strong> Donors can donate their new or used gear in exchange for D-Tokens. With enough D-Tokens,
                        they can be used to purchase new gear from our sponsor company.</h4>
                    
                </div>
                <div class = "col-sm-4">
                    <span class = "glyphicon glyphicon-transfer logo"></span>
                </div>
            </div>
        </div>
        
        <div id="portfolio" class = "container-fluid text-center bg-grey">
            <h2>Portfolio</h2>
            <h4>Things that you can donate</h4>
            <div class="row text-center">
                <div class = "col-sm-4">
                    <div class = "thumbnail">
                        <img src = "{% static 'img/jordan.png' %}" alt="Shoes">
                        <p><strong>Basketball Shoes</strong></p>
                        <p>Any brand or size - as long as they are usable.</p>
                    </div>
                </div>
                <div class = "col-sm-4">
                    <div class = "thumbnail">
                        <img src = "{% static 'img/clothes.png' %}" alt="Clothes">
                        <p><strong>Clothes</strong></p>
                        <p>Athletic clothes fit for playing basketball in.</p>
                    </div>
                </div>
                <div class = "col-sm-4">
                    <div class = "thumbnail">
                        <img src = "{% static 'img/accessories.jpg' %}" alt="Access.">
                        <p><strong>Accessories</strong></p>
                        <p>Accessories used to play basketball, such as socks and headbands.</p>
                    </div>
                </div>
            </div>
            
            
            
        </div>

        <div id="contact" class = "container-fluid bg-grey">
            <h2 class = "text-center">CONTACT</h2>
            <div class = "row">
                <div class = "col-sm-5">
                    <h2>Ask us questions.</h2>
                    <p>Contact us and we'll get back to you within 24 hours.</p>
                    <p><span class = "glyphicon glyphicon-map-marker"></span> Seoul, Korea</p>
                    <p><span class = "glyphicon glyphicon-phone"></span> +82 10-6502-3459</p>
                    <p><span class = "glyphicon glyphicon-envelope"></span> seho.jeong19@stu.siskorea.org</p>
                </div>
                <div class = "col-sm-7">
                    <div class = "row">
                        <div class = "col-sm-6 form-group">
                            <input class = "form-control" id="name" name="name" placeholder = "Name" type = "text" required>
                        </div>
                        <div class = "col-sm-6 form-group">
                            <input class = "form-control" id="email" name="email" placeholder="Email" type = "email" required>
                        </div>
                    </div>
                    <textarea class = "form-control" id="comments" name = "comments" placeholder = "Comment" rows = "5"></textarea>
                    <br>
                    <div class = "row">
                        <div class = "col-sm-12 form-group">
                            <button class = "btn btn-default pull-right" type="submit">Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class = "container-fluid text-center">
            <a href="#myPage">
                <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
            <p>Bootstrap Theme Made By <a href="http://daddyslab.com/">Daddy's Lab</a>
            </p>
        </footer>
    </body>












</html>

templates/manual_donee.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>DONOR-HUB</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">

        
        <style>
            .jumbotron{
                background-color: orangered;
                color: white;
            }
            .bg-grey{
                background-color: #f6f6f6;
            }
            .container-fluid{
                padding: 60px 50px
            }
            .logo{
                color: orangered;
                font-size: 200px;
            }
            .logo-small{
                color: orangered;
                font-size: 50px;
            }
            .thumbnail{
                padding: 0 0 15px 0;
                border: none;
                border-radius: 0;
            }
            .thumbnail img{
                width: 100%;
                height: 200px;
                margin-bottom: 10px;
            }
            .carousel-control.right, .carousel-control.left{
                background-image: none;
                color: #f4511e;
            }
            .carousel-indicators li{
                border-color: #f4511e;
            }
            .carousel-indicators li.active{
                background-color: #f4511e;
            }
            .item h4{
                font-size: 19px;
                font-style: italic;
                margin: 70px 0;
            }
            .myCarousel1_img{
                width: 100%;
                height: 500px;
            }
            .panel{
                border: 1px solid #f4511e;
                border-radius:0;
                transition: box-shadow 0.5s;
            }
            .panel:hover{
                box-shadow: 5px 5px 40px lightgray;
            }
            .panel-footer .btn:hover{
                border: 1px solid #f4511e;
                background-color: #fff;
                color: #f4511e;
            }
            .panel-heading{
                color: #fff !important;
                background-color: #f4511e !important;
                padding: 25px;
            }
            .panel-footer{
                background-color: #fff !important;
            }
            .panel-footer h3{
                font-size: 32px;
            }
            .panel-footer h4{
                color: #aaa;
                font-size: 14px;
            }
            .panel-footer .btn{
                margin: 15px 0;
                background-color: #f4511e;
                color: #fff;
            }
            .navbar{
                background-color: orangered;
                border: 0;
                font-size: 12px;
                letter-spacing: 4px;
            }
            .navbar li a, .navbar .navbar-brand{
                color: #fff !important;
            }
            .navbar-nav li a:hover, .navbar-nav li.active a{
                color: orangered !important;
                background-color: #fff !important;
            }
            .navbar-default .navbar-toggle{
                border-color: transparent;
            }
            
            body{
                font-family: Lato, sans-serif;
            }
            .jumbotron{
                font-family: Montserrat, sans-serif;
            }
            .navbar{
                font-family: Montserrat, sans-serif;
            }
            footer .glyphicon{
                font-size: 20px;
                margin-bottom: 20px;
                color: orangered;
            }


        </style>
        
    </head>
    
    <body id="myPage" data-spy="scroll" data-target=".navbar">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'mainpage_ex' %}">DONOR-HUB</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'mainpage_ex' %}">ABOUT</a></li>

                        <li><a href="{% url 'mainpage_ex' %}">PORTFOLIO</a></li>
                        <li><a href="{% url 'manual_home' %}">MANUAL</a> </li>

                        {% if user.is_active %}
                        <li><a href="{% url 'password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'logout' %}">LOGOUT</a></li>
                        {% else %}
                        <li><a href="{% url 'register' %}">JOIN</a></li>
                        <li><a href="{% url 'login' %}">LOGIN</a></li>
                        {% endif %}
                        <li><a href="{% url 'photo:index' %}">THE HUB</a></li>
                        {% firstof user.get_short_name user.get_username %}
                    </ul>

                </div>


            </div>
        </nav>
        <!-- ------------------------------------------------------------- -->
        
        <div class="jumbotron text-center">
            <h1>DONOR-HUB</h1>
            <h3>Manual: For Donees</h3>
        </div>
        
        <!-- ----------------------------------------------------------- -->
        
        <div id="about" class="container-fluid">
            <div class="row">
                <div class="col-sm-8">
                    <h1>Step 1</h1>
                    <p>Click "Join" on the menu bar above and choose the "Donee" option.
                        Carefully read the description that come with the options.
                        Input neccessary information to complete your registration. </p>
                    
                </div>
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-pencil logo"></span>
                </div>
            </div>
        </div>
        
        <div class="container-fluid bg-grey">
            <div class="row">
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-ok logo"></span>
                </div>
                <div class="col-sm-8">
                    <h1>Step 2</h1>
                    <p>Now you are ready! Enter "The Hub" to browse through your options of various athletic gear.
                        Once you have found something to your taste, simply click the button to choose the good.
                        Once you are viewing the product, scroll down to comment on the page to show interest.
                        We will notify you if you have been selected to receive the product.
                        Remember that the amount of selections you can make are limited, so choose wisely!</p>
                </div>
            </div>
        </div>
        
        <!-- ----------------------------------------------------------- -->
        
        <div id="about" class="container-fluid">
            <div class="row">
                <div class="col-sm-8">
                    <h1>Step 3</h1>
                    <p>Now you just wait! Your good is on its way directly to you and once it arrives,
                        please send a verification photo to our email in order for us to know that you got what you wanted!  </p>
                    
                </div>
                <div class="col-sm-4">
                    <span class="glyphicon glyphicon-home logo"></span>
                </div>
            </div>
        </div>
        
        
        
            
        <footer class="container-fluid text-center">
            <a href="#myPage">
                <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
            <p>Bootstrap Theme Made By <a href="http://daddyslab.com/">Daddy's lab</a></p>
        
        </footer>
        
    </body>
</html>